version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    
    environment:
      DB_HOST: {}
      DB_PORT: {}
      DB_USER: {}
      DB_PASSWORD: {}
      DB_NAME: {}
      JWT_SECRET: {}
      GEMINI_KEY: {}
    depends_on:
      postgres:
        condition: service_healthy
    # Use Google DNS to fix NXDOMAIN
    dns:
      - 8.8.8.8
      - 8.8.4.4
    # Optional: increase network timeout and make container more resilient
    restart: unless-stopped
    networks:
      - nordik-network

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: {}
      POSTGRES_DB: {}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 10
    networks:
      - nordik-network

volumes:
  pgdata:

networks:
  nordik-network:
    driver: bridge
